### ISSUE TITLE
2020-22 typos in Limitations on public access guidance (Peter P, September 2020)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#10]
https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series#25 - INSPIRE reason a has “authorites” and f has confidentality.

**Comment by 6footdestiny** [comment]
Simples. Fix typos

**Comment by PeterParslow** [comment]
2021-06-02 meeting - just fix it!

**Comment by PeterParslow** [comment]
Fixed during migration to GitHub publication
