### ISSUE TITLE
Use constraints: inconsistency of "Encoding Guidance" with "Guidance" and Encoding Example 3

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#104]
At https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series/#23:

"Guidance" 2 says "If no conditions apply, then 'no conditions apply' should be recorded." [this is in line with INSPIRE TG]

"Encoding Guidance" 8 says "If there are no limitations the value of gmd:otherConstraints shall be 'no limitations' (see Example Three)." - probably incorrectly copied from Element 25 / Encoding Guidance 4.

Example three follows Guidance 2. [this is in line with INSPIRE TG]

Propose: correct Encoding Guidance 8.

**Comment by nmtoken** [comment]
or just remove Encoding Guidance 8.

**Comment by archaeogeek** [comment]
Verified fixed in https://github.com/agiorguk/gemini/pull/181
