### ISSUE TITLE
2020-25 Conformity specification date (INSPIRE Validator; Peter)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#12]
INSPIRE TG Requirement C.21 states “The date type code element gmd:date/gmd:CI_Date/gmd:dateType/gmd:CI_DateTypeCode shall be given and it shall point to the value "publication" of the ISO 19139 code list CI_DateTypeCode” (my emphasis)
GEMINI Conformity domain states “a date type (creation, revision, or publication)”.
Without a publication date, the record fails the INSPIRE reference validator.

It may be worth changing “At least one conformity statement shall be to an INSPIRE specification” to “At least one conformity statement shall be to an INSPIRE regulation” which is the phrase used above TG Requirement C.20 (that uses the phrase “Implementing Rule”)

**Comment by archaeogeek** [comment]
I'm not sure that the proposed guidance change is clear enough to help users why their record might be failing validation. My feeling is that the guidance notes would benefit from a bit of a re-order and re-word, perhaps with a link to the relevant INSPIRE TG on the subject.

**Comment by PeterParslow** [comment]
For the first paragraph, see https://github.com/INSPIRE-MIF/helpdesk-validator/issues/479

**Comment by archaeogeek** [comment]
I've just realised that my comment is a little off-topic for this specific issue. Anyhow... my preference for the guidance notes for conformity in general is that we should make it explicit that records must include conformance to Regulation 1089/2010, since this is in the schematron and hence required for Gemini validity as well as INSPIRE. I don't think the current guidance and examples make it clear. We should also provide a hyperlink to the regulations. I would suggest something like the following:

> 1. Datasets and dataset series must declare conformity to [Regulation 1089/2010], however it is valid to say that the dataset or series is not conformant or has not been tested. See the first encoding example below for the correct encoding.
> 2. Other conformity statements may be added, citing INSPIRE technical guidance or other specifications
> 3. State the data specification to which the degree of conformity applies, and optionally an 'Explanation', for example to reference the conformance criteria in the specification against which conformance is being claimed.
> 4. Assess the conformity of the data resource against its product specification or the INSPIRE thematic data specification.
> 5. There must be one conformity statement relating to each specification.
> 
> Note that for full INSPIRE validation a date of type "publication" must be provided for each cited specification.

I would also make the "not assessed against Regulation1089/2010" example encoding the first in the list.

**Comment by PeterParslow** [comment]
> 5. There must be one conformity statement relating to each specification

Isn't this redundant, given point 1? 

I guess it's just my ISO/OGC standard writing hat, but I wonder if we should change "must" in number one to "shall"? 

I wonder if 4 should come before 3, and perhaps even first, given you have to assess it (or decide to declare 'not tested', I suppose) before you can state the degree.

**Comment by PeterParslow** [comment]
2021-07-1: 
+1 to "shall"
Users still find it confusing; would a flow chart help? @6footdestiny to draft a flow chart to embed in the guidance 
@PeterParslow to ask Blue Star how they would like to receive such graphics.

**Comment by 6footdestiny** [comment]
initial stab at a graphic 
![conformity](https://user-images.githubusercontent.com/5612032/124480219-f29ed980-dd9e-11eb-8637-6ba32a405618.png)

**Comment by 6footdestiny** [comment]
![conformity](https://user-images.githubusercontent.com/5612032/125420113-233e5d1b-b998-477b-9550-bb0352c25530.png)

**Comment by PeterParslow** [comment]
The flow chart needs pass / fail / not assessed against INSPIRE - but also allow for metadata creators to assert conformance to other specs. Consider it from the metadata creator's perspective. Make it clear that you need to make a conformity statement to INSPIRE even if you don't conform.

@PeterParslow  to work up an alternative flow chart.

**Comment by PeterParslow** [comment]
Different "issue" but may as well fix while on this element: even for the 'service' view, item 1 of the Guidance says "even if simply to say that the data set is ..."

**Comment by PeterParslow** [comment]
How about this? Still a bit ugly, but I think it's complete. If we agree, then I/we need to tease apart the Data/Service parts.

(Turns out that Enterprise Architect is a bit of a pain for flow charts, trying to impose some strict rules that I know nothing about!). But Word doesn't automatically join connectors....)
![Conformity flow chart](https://user-images.githubusercontent.com/8492193/126634301-1743c7f6-d5d8-4b5d-a1e4-f6430e9f781d.png)

**Comment by nmtoken** [comment]
> I thought "not evaluated" wasn't allowed anymore,

I think previously you could omit the dataQuality section if you hadn't done the evaluation, but now you must supply a dataQuality  section, and explicitly state not evaluated (in a proscribed manner)

**Comment by PeterParslow** [comment]
> in a proscribed manner

prescribed ;)

**Comment by PeterParslow** [comment]
@Peter: Describe how you can include an "explanation" on your INSPIRE conformity statement - a little "grey box" after a join of the three "degrees". 
@archaeogeek: suggest some improved words

**Comment by archaeogeek** [comment]
Potential revised text:

1. For Gemini compliance, you must provide a conformity statement referring to the INSPIRE specifications, even if the dataset is not conformant, or you didn't test it.
2. Datasets and dataset series shall declare conformity to [INSPIRE Regulation 1089/2010] and shall use the title and citation date in the example and encoding guidelines below.
3. Other conformity statements may be added, where each conformity statement shall relate to only one specification.
4. State the data specification to which the degree of conformity applied and optionally an 'Explanation', for example to reference the conformance criteria in the specification against which conformance is being claimed.

**Comment by PeterParslow** [comment]
Other parts of 'Conformity' could be made more user friendly, e.g. 

Replace "The purpose of this element is to identify the conformity of the data resource to the cited specification" with "Does the resource comply with the specification?"

@PeterParslow to draft a re-worded text for the whole element, incorporating Jo's words.

**Comment by archaeogeek** [comment]
@archaeogeek to change guidance point 1 to "shall" and remove services- check for rewording of services version
