### ISSUE TITLE
Broken links from https://agiorguk.github.io/gemini/1048-uk-gemini-encoding-guidance.html

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#153]
The links from the general XML encoding guidance to the detailed "dataset" and "services" pages don't work (didn't survive / got forgotten about during migration & restructure).

They seem to be local URLs "datasets.html" and "services.html", rather than "1062-gemini-datasets-and-data-series.html" and "1063-gemini-services.html"

**Comment by archaeogeek** [comment]
Confirmed closed on dev branch

**Comment by archaeogeek** [comment]
Verified fixed in https://github.com/agiorguk/gemini/pull/181
