### ISSUE TITLE
2020-29 Some need to provide author names not roles (Graham Parton, Science and Technology Facilities Council / Rutherford Appleton)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#16]
For example, I’ve been looking at the ‘Responsible Organisations’ section today and found that this is quite at odds with how data archives work when it comes to the role of author. The guidance documentation seems to be well suited for organisations which have geospatial data (e.g. OS), where individuals may change but the products continue to be issued by the organisation. However, in the scientific archives such as those from the NERC data centres (one of which I work for), our assets are published with named people as the authors. With GDPR we are unlikely to be able to release information about their organisation and email address (both marked as mandatory elements for this component) for individuals without their consent, which may be hard to establish for our historic archive going back a number of decades – indeed some authors are now deceased. Consequentially, we’re having to adapt the content we provide to include these required elements but with content that is less than useful (basically ‘unavailable to comply with GDPR.’).

**Comment by 6footdestiny** [comment]
I believe recent changes proposed fro GUF may address this. Not sure if they'll proceed to formal adoption by ISO/OGC. May be more pragmatic to record 'author' as in peer review context elsewhere - addionalInfo/lineage?

**Comment by PeterParslow** [comment]
2021-07-01: also done by CEH, where CEH "own", but there are individual named authors listed as well.

Could be GEMINI Responsible organisation, with role of "author" or "principal investigator".

How comfortable are we with "Responsible organisation" being used for individuals? We derive the term "Responsible organisation" from INSPIRE, creating it as that in GEMINI 2.

**Comment by nmtoken** [comment]
Perhaps check how individuals are catered for in ESAA on registering data

**Comment by nmtoken** [comment]
_However, in the scientific archives such as those from the NERC data centres (one of which I work for), our assets are published with named people as the authors._

Note the Principal Investigator for any NERC grant (https://nerc.ukri.org/funding/application/howtoapply/forms/grantshandbook/) must be a member of an organisation:

> The Principal Investigator on the proposal must be resident in the UK and be employed
by an eligible UK Research Organisation (Higher Education Institution, Research
Council Institute or a recognised Independent Research Organisation). Employment
should be at lecturer (or equivalent) level or above.

**Comment by gap736uk** [comment]
> _However, in the scientific archives such as those from the NERC data centres (one of which I work for), our assets are published with named people as the authors._
> 
> Note the Principal Investigator for any NERC grant (https://nerc.ukri.org/funding/application/howtoapply/forms/grantshandbook/) must be a member of an organisation:
> 
> > The Principal Investigator on the proposal must be resident in the UK and be employed
> > by an eligible UK Research Organisation (Higher Education Institution, Research
> > Council Institute or a recognised Independent Research Organisation). Employment
> > should be at lecturer (or equivalent) level or above.

PIs is a particular role related to the data and may or may not be on the formal author list. For example, data authors may be post-docs or other project participants or, in the case of data outside the academic funding route, not actually related to a given project per se. Indeed, does this have scope for individuals (E.g. amature meteorologists) who make data available but not within any organisation and are stored with a recognised repository publishing using GEMINI?

The need here is to make sure that the appropriate parties - regardless of whether they are an organisation or a named individual - are able to get suitable exposure. 



From the academic publishing side of things we have

**Comment by PeterParslow** [comment]
ISO 19115:2003's CI_ResponsibleParty has an optional (single) individualName field. This can be used under our general "extensibility" clause.

We say "Do not identify an individual by name, as this is subject to change without warning and the information is impossible to keep up-to-date." as a rule for 'contact position' (CI_ResponsibleParty.positionName)

Add to element Guidance (extending bullet 2?) "Where you want to identify an individual by name, use CI_ResponsibleParty.positionName".

**Comment by archaeogeek** [comment]
Confirm fixed on dev branch

**Comment by archaeogeek** [comment]
Verified fixed in https://github.com/agiorguk/gemini/pull/181
