### ISSUE TITLE
2021-04 Date of Publication - Corresponding element in other standards mention of INSPIRE (Sean Gaffney, Feb 2021)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#22]
See https://www.agi.org.uk/gemini/40-gemini/1063-gemini-services#8 as it states, under the Comparison column, that INSPIRE only allows a single instance for services. This is not correct according to INSPIRE TG 2017 - it is Date of Creation and Date of Revision that should only have a single instance. Date of publication allows multiplicity in INSPIRE.

**Comment by archaeogeek** [comment]
Confirm fixed in live branch
