### ISSUE TITLE
2020-02: “Which metadata should be inherited by individual elements/features/entities within the dataset?” (asked by Nick Nisbet, April 2018)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#24]
clarify this in GEMINI somewhere

**Comment by PeterParslow** [comment]
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1037-uk-gemini-standard-and-inspire-implementing-rules already said “not everything in a GEMINI record can be assumed to be true individually for each feature instance in the resource”

**Comment by 6footdestiny** [comment]
I think the informal pictorial UML class relationship might help address this. The class diagram should be added to the document.

**Comment by PeterParslow** [comment]
Sean: does this cause a problem to anyone else?
Jo: looking at feature level metadata, so this may come up - but hasn't yet. Logically, restrictions would apply.
James P: surely everything in the metadata must apply to each instance?
Peter: perhaps not quality statements

Could we allow / comment that a GEMINI record is at the dataset level, but that the same elements can be used (with different hierarchyLevel) for feature instance metadata?

Strengthen the statement in the 'home page' that GEMINI is about dataset discovery metadata; mention that some elements can be use at the instance level, but this is not the scope of GEMINI.

**Comment by PeterParslow** [comment]
Peter to draft wording; once the words are agreed, it can go straight to publication, not needing to wait for a release.

**Comment by PeterParslow** [comment]
Existing statement:

> Note that GEMINI (and the INSPIRE Guidance) are about metadata for datasets, series, and services (collectively, 'resources'); not everything in a GEMINI record can be assumed to be true individually for each feature instance in the resource. The underlying ISO standards (19115, 19139) do allow for metadata at the instance level

I recommend adding:

> , so the elements could be used to describe metadata for that, but the guidance here may not be appropriate and the resulting record could not be validated as a GEMINI (or INSPIRE) record.

Revised page attached (as a Word file): 
[1037-uk-gemini-standard 2-3 revised.docx](https://github.com/agiorguk/gemini/files/6521576/1037-uk-gemini-standard.2-3.revised.docx)

**Comment by PeterParslow** [comment]
See https://github.com/agiorguk/gemini/issues/31, a DD3 suggestion which would affect the same page. Perhaps we should resolve that one too to avoid sending two revisions of the same page to the AGI support company too close together?

**Comment by PeterParslow** [comment]
Included in marked up file added to pending and emailed to AGI web support company to replace https://www.agi.org.uk/gemini/40-gemini/1037-uk-gemini-standard-and-inspire-implementing-rules/

**Comment by PeterParslow** [comment]
1037-uk-gemini-introduction.html was created during migration to GitHub publication, but is not currently used.

If the AGI site redirected to https://agiorguk.github.io/gemini/1037-uk-gemini-introduction.html rather than https://agiorguk.github.io/gemini/1037-uk-gemini-standard-and-inspire-implementing-rules.html, and all other pages "return to GEMINI 2.3 home page" links were to 1037-uk-gemini-introduction.html then:

a) this & #31 would be fixed
b) 1037-uk-gemini-standard-and-inspire-implementing-rules.html would be redundant & deleted.
