### ISSUE TITLE
2020-13 Text for guidance on use of service metadata elements (from Sean, April 2020)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#3]
The text content in [GEMINI - Services](https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1063-gemini-services#18) is not always directly appropriate for service metadata instances. An example is that Spatial Resolution contains a full suite of guidance on use, but it can’t actually be encoded in service XML so this guidance is not directly applicable to services. Other elements contain textual references to datasets and series.. I recommend a review of the textual content of all the service metadata elements to ensure they are appropriate.

**Comment by PeterParslow** [comment]
JP: The guidelines do say though this though ~ For services, it is not possible to express the restriction of a service concerning the spatial resolution in using the ISO 19139 XML Schema.
It shall be expressed in the Abstract.
The spatial resolution restriction text shall include either an equivalent scale as integer valued scale denominator or a resolution distance using a numerical length value and with a unit of length.

**Comment by PeterParslow** [comment]
2021-07-01: only three present, who agree with JP - suggest this is closed ("no change required"). @Sgaff

**Comment by PeterParslow** [comment]
2021-16-07: there are still bits of text in the "services" page that mention datasets & series. The main point is for a general review of the page to tidy these up.

**Comment by Sgaff** [comment]
Hi, I've got down to Limitations on Public Access and these are my observations so far:

Abstract
Corresponding elements in other standards - references 19115:2203 MD_Identification.abstract

Alternative title:
Guidance note 2 - change "other names used for the dataset" to "other names used for the dataset or service"
Corresponding elements in other standards - again a reference to ISO 19115:2003 MD_Identification

Bounding box:
Encoding guidelines. Guidelines 1 - references datasets, not services. 

Conformity:
Definition should be changed from 'data' to 'resource'. 
Guidance 1 needs to change from 'data set' to 'resource'

Dataset reference date:
Is element name incorrect? This is for service metadata, not datasets. 
Corresponding element in other standards - references ISO 19115:2003 MD_Identification.citation
Encloding guidelines note 1 needs to refere to service reference date (probably - if we decide element name needs to change)

Equivalent scale:
Should probably be dropped as an element for services as encoding guidelines specify spatial resolution shall be expressed in the Abstract for services. 

Keyword
Corresponding elements in other standards - again a reference to ISO 19115:2003 MD_Identification
Encoding guidance - example 5. Should this be dropped as it is not to be used?

Limitations on Public Access
Purpose and Meaning and Comment text to replace 'data' with 'data resource'
Corresponding elements in other standards - again a reference to ISO 19115:2003 MD_Identification; 

I will continue on the remaining text in the next few days

Sean

**Comment by Sgaff** [comment]
Use constraints:
Purpose and Meaning and Comment text need to change text from 'data' to 'data resource'. 
Corresponding element in other standards - again a reference to MD_Identification
Encoding guidelines inconsistency. Guideline 2 refers to the MD_LegalConstraints element whereas Guideline 5 refers to the LegalConstraints element. Suggest MD_LegalConstraints is used in both cases for consistency and accuracy.

**Comment by Sgaff** [comment]
I've now completed my review - only outstanding area that needs work is Vertical Extent information.
* I think we need to review in detail the Purpose and Meaning, and the Guidance, so it is clear exactly how this element should be applied to metadata for services. Currently, I believe its unclear e.g. is the element to record the vertical domains of each data resource the service operates on, or is it something else?
* Encoding guidance note 1 is extremely verbose and ambiguous in my opinion. Think it also needs to be re-assessed and re-worded for clarity.
* Encoding guidance note 2 quotes "must be provided in order to give meaning to the minimum and maximum coordinates". There is not a useful subsequent sentence detailing what "in order" means.
* Encoding examples 1 and 2 use MD_DataIdentification when they should be using SV_ServiceIdentification

**Comment by archaeogeek** [comment]
Closed in favour of individual issues for each element requiring a change, as per meeting minutes at https://github.com/agiorguk/gemini/wiki#2023-10-04
