### ISSUE TITLE
DD3 R1 Introduce GEMINI in the context of wider principles

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#31]
This recommendation arose from Peer Review comments while drafting this document. That is, some of the peer review organisations feel that GEMINI should promote itself more, in the context of things like the UK National Data Strategy.
GEMINI supports several aspects of good data management, such as making it easier to find and access the data. At the moment, these are framed in the National Data Strategy and Location Data Strategy. The GEMINI introductory pages should make more of this relationship in order to make it clearer how an organisation can benefit from adopting GEMINI.
It would also be useful to link to the UK government guidance that recommends public authorities to use GEMINI, and to provide links to related resources such as GEMINI software implementations.

**Comment by PeterParslow** [comment]
There are also general recommendations from the "Data Discoverability" projects about writing this page in a more user friendly way. Here is a revised word document, with the small change from #24 and more extensive changes related to this issue.
[1037-uk-gemini-standard 2-3 revised for issue 2020-02 and DD3 R1.docx](https://github.com/agiorguk/gemini/files/6521757/1037-uk-gemini-standard.2-3.revised.for.issue.2020-02.and.DD3.R1.docx)

**Comment by PeterParslow** [comment]
2021-06-08: inconsistent between "UK GEMINI" and "GEMINI". Go for "UK GEMINI" on first use, but introduce "(also known as GEMINI)". Change occurrence in third paragraph to just "GEMINI".

Should first spell out the acronym.

Move the GDS recommendation sentence into the first paragraph, as second sentence.

See also #58.

**Comment by PeterParslow** [comment]
Emailed to Blue Star (AGI web support)

**Comment by PeterParslow** [comment]
Note: this issue has not (yet) been included in the text migrated to GitHub. I will therefore move it "back" from "With AGI to publish" to "Pending release". Same applies to #58.

#24 has been implemented (on GitHub)

**Comment by archaeogeek** [comment]
Closed- @archaeogeek to get link on main AGI website changed to new intro page
