### ISSUE TITLE
DD3 R14 element Resource locator, linkage sub-element

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#53]
See #13 (GEMINI bug tracker 2020-26.)

Expand guidance on “function” sub element to match the useful distinction in DCAT and clarify which values apply when, based on INSPIRE Metadata TG p104.
Mention that WMS is “information” (INSPIRE Metadata TG example at C.2.4), and “download” “SHOULD be used for the URL at which this distribution is available directly, typically through a HTTP Get request.” (DCAT:downloadURL)

**Comment by Sgaff** [comment]
Question about the function sub-element: many portals these days have a search function that leads to a download function - how should that use case be captured?

**Comment by KoalaGeo** [comment]
![image](https://user-images.githubusercontent.com/33657876/120492646-28246180-c3b2-11eb-9e92-16e69231a7df.png)

![image](https://user-images.githubusercontent.com/33657876/120492593-1e9af980-c3b2-11eb-8b72-8ce58e303cc4.png)

**Comment by KoalaGeo** [comment]
`
<gmd:URL>http://example.com/wfs?VERSION=2.0.0&amp;SERVICE=WFS&amp;REQUEST=GetFeature&amp;STORE
DQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&amp;ID=123345</gmd:URL>
 </gmd:linkage>
 <gmd:name>
 <gco:CharacterString>WFS GetFeature request for downloading the data
set</gco:CharacterString>
 </gmd:name>
 <gmd:function>
 <gmd:CI_OnLineFunctionCode

codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode"
 codeListValue="download" />
 </gmd:function>
 </gmd:CI_OnlineResource>
 </gmd:onLine>
 </gmd:MD_DigitalTransferOptions>
</gmd:transferOptions>
Example 3.9: Data set resource l
`

**Comment by PeterParslow** [comment]
Notes from DD3: 

Three DCAT2 tags:

- “dcat:landingPage” 19115 function = information
- “dcat:accessURL, 19115 function = information. Note: accessURL is more relevant where the target page then allows download. 
- “dcat:downloadURL” where 19115 function = download. 

Mention that WMS is “information” (INSPIRE Metadata TG example at C.2.4), and “download” “SHOULD be used for the URL at which this distribution is available directly, typically through a HTTP Get request.” (DCAT:downloadURL)

**Comment by PeterParslow** [comment]
2021-06-21: Peter to draft suggested revised wording.

**Comment by PeterParslow** [comment]
Add to https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series/#19 Guidance:

6. Guidance on selecting appropriate OnLineFunctionCode value for function sub-element. 

| OnLineFunctionCode  | Meaning                                                                                | Example                |
|---------------------|----------------------------------------------------------------------------------------|------------------------|
| download            | online instructions for transferring data from one storage device or system to another | WFS Direct URL to file |
| information         | online information about the resource                                                  | WMS Product page       |
| offlineAccess   | online instructions for requesting the resource from the provider                      |                        |
| order           | online order process for obtaining the resource                                        | Product ordering page  |
| search          | online search interface for seeking out information about the resource                  |                        |

**Comment by archaeogeek** [comment]
Confirmed fixed in dev branch
