### ISSUE TITLE
List implementations in order to help first time users

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#58]
It would be helpful to first time users if GEMINI indicated some implementations. This could also help adoption by showing that there are tools available.

Suggestions include:

GeoNetwork Open Source GEMINI plugin
UK Location Metadata Editor
MEDIN metadata editor(s)

I note that ESRI UK have stopped working on their own implementation. Perhaps say something about how similar/different an INSPIRE metadata editor would be?

**Comment by PeterParslow** [comment]
Jo: "My suggestion would be to come up with some draft content that I can put to <AGI Council> - I think that will be easier than getting agreement to something abstract."

How about doing this in the context of a major re-write of https://www.agi.org.uk/gemini/40-gemini/1037-uk-gemini-standard-and-inspire-implementing-rules/ (including changing the page title!):

Add
----------------
**Software that implements GEMINI 2.3**
Several software implementations exist and are in use across the UK:

- [UK Location Metadata Editor](https://locationmde.data.gov.uk/): online editor owned by the Defra INSPIRE team
- [GeoNetwork Open Source](https://geonetwork-opensource.org/) [GEMINI plugin](https://github.com/AstunTechnology/iso19139.gemini23): server software in use in several government departments
- [MEDIN metadata editors](https://www.medin.org.uk/data/submit-metadata): online and downloadable client editors for the MEDIN community profile
----------------
@archaeogeek : is that link to the correct version of the GEMINI plugin?

**Comment by archaeogeek** [comment]
@PeterParslow that repository for iso19139.gemini23 is the canonical one, but https://github.com/metadata101/iso19139.gemini23 is automatically kept up to date with it. The only thing is that I'm more likely to see issues/discussion/comments on the Astun version than the other!

**Comment by PeterParslow** [comment]
> @PeterParslow that repository for iso19139.gemini23 is the canonical one, but https://github.com/metadata101/iso19139.gemini23 is automatically kept up to date with it. The only thing is that I'm more likely to see issues/discussion/comments on the Astun version than the other!

@archaeogeek: I don't think this comment belongs to this issue (or even to this repository!)

**Comment by archaeogeek** [comment]
@PeterParslow perhaps I should rephrase it... you asked if the link to iso19139.gemini23 was to the correct repository for the GeoNetwork Gemini plugin- and yes, it is, but there is also https://github.com/metadata101/iso19139.gemini23, which is kept up to date with it, and my be preferable because it's less "Astun". Does that make more sense now?

**Comment by PeterParslow** [comment]
Yes; sorry!

**Comment by Sgaff** [comment]
MEDIN would be keen on this

**Comment by PeterParslow** [comment]
2021-06-08:
Add this to the new 'home page'

**Comment by PeterParslow** [comment]
Included in marked up file added to pending and emailed to AGI web support company to replace https://www.agi.org.uk/gemini/40-gemini/1037-uk-gemini-standard-and-inspire-implementing-rules/

**Comment by PeterParslow** [comment]
Remove mention of UK Metadata Editor
Included in https://github.com/agiorguk/gemini/pull/112
