### ISSUE TITLE
Typo in element 51 Guidance

### ISSUE THREAD

**Issue by archaeogeek** [agiorguk/gemini#60]
https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series/#51 guidance has "If more than one charater encoding"- it should be "character"

**Comment by PeterParslow** [comment]
2021-07-1: fix

**Comment by PeterParslow** [comment]
Fixed on Peter's laptop, 2021-07-NN

**Comment by PeterParslow** [comment]
Fixed sometime during migration to GitHub publication
