### ISSUE TITLE
Add Metadata standard version & name to "XML Element order" page

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#62]
Need to update https://www.agi.org.uk/gemini/40-gemini/1046-xml-element-order/ to include elements introduced since April 2018: Metadata standard version, Metadata standard name

**Comment by PeterParslow** [comment]
https://github.com/agiorguk/gemini/pull/155 should resolve this

**Comment by archaeogeek** [comment]
Confirmed resolved on dev branch

**Comment by archaeogeek** [comment]
Verified fixed in https://github.com/agiorguk/gemini/pull/181
