### ISSUE TITLE
How to manage & publish GEMINI pages

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#64]
GEMINI consists of (about) 15 web pages. Twelve are "normal" web pages; three are generated from common content, but are currently sent to AGI as HTML web pages. The "[XML Element Order](https://www.agi.org.uk/gemini/40-gemini/1046-xml-element-order/)" page would also benefited from being generated from that common content - it has fallen behind.

The current issues may impact perhaps 12 of those 15 pages.

BlueStar, who host AGI's website, expect to be paid for each set of changes. This is an issue across the website that will be discussed at AGI Council. @archaeogeek to keep us informed.

Some or all the GEMINI pages could be published separately (e.g. on GitHub), styled (to some extent) like the AGI site, and linked from there. We would want the permanent links to remain, so there would be quite a lot of redirects.

As a separate question, we could use GitHub to generate the web pages, allowing us to maintain them "natively" within GitHub in Markdown.

**Comment by PeterParslow** [comment]
At meeting on https://github.com/agiorguk/gemini/wiki#2021-07-29 we agreed to move the "element" pages to GitHub, which I take to mean pages 1062, 1063 and 1250.

I have spent a merry few hours tracing all the links & updating the old "Readme" file that documented the old site at go live (2018). We seem to have added a lot more links (or I missed some back then).

Anyway, you can see the current picture (in words & image) at https://github.com/agiorguk/gemini/blob/main/resources/Readme.md

I reckon there are four pages that should have been deleted earlier; another two that are not really any use:
- 1047 Bibliography - why not just have the links to the targets?
- 1040 Conformity - always been a rather short list!

I would favour moving all the pages on to GitHub. 

We have pending versions of 1037 & 1048 already, leaving seven "text" pages most of which could do with updates.

**Comment by archaeogeek** [comment]
Skeleton page for outlining the update process:
https://github.com/agiorguk/gemini/blob/main/governance/website_update_process.md

**Comment by PeterParslow** [comment]
I've had some success just putting 'plain HTML' in a repository and using GitHub Pages: https://github.com/PeterParslow/GEMINI2-3

Like most Content Management Systems, the CSS approach taken on the AGI website is pretty opaque, so I haven't managed to reproduce the 'look & feel', but that aside, do have a look.

**Comment by archaeogeek** [comment]
For information, the gh-pages version is at https://peterparslow.github.io/GEMINI2-3/

**Comment by PeterParslow** [comment]
I've just added a sample with dynamic (dataset / service) content - one element (Title). There may be more elegant ways to do it!

Still can't get the CSS to work :(

**Comment by archaeogeek** [comment]
@PeterParslow do you have a simple css that you're trying to include? I'm certain you should be able to reference one. That might be simpler than trying to link to the ones actually used on the AGI website. I think as long as we hit the basic look and feel stuff it should be OK, particularly for now. I love the dynamic page though- it's great!

**Comment by PeterParslow** [comment]
Something for later: https://openwork-nz.github.io/mdwg/defs/TableOfContents

That is, I think there are nice ideas in this New Zealand / Australia guidance, not that we should try to achieve that structure/output for GEMINI at this point!

**Comment by PeterParslow** [comment]
Looking down the ASCII Doc / Metanorma route:

- Metanorma does seem to support the ASCII Doc "include" directive (an extension defined by ASCIIDoctor). I can't see anything about it in the Metanorma authoring guide (https://www.metanorma.org/author/topics/document-format/), but this blog implies support: https://www.metanorma.org/blog/2020-12-08-asciidoc-include/

However, to use "include", 

- we’d have to manage two files (datasets, services) with the common stuff in a whole lot of includes
- I can't imaging anyway to generate the Summary page
- I can't see how we can support our common case, where text in one cell in a table differs between dataset & service - so we would have to completely re-think our layout.
- I can't see any way to provide the expand/collapse functionality that we use to make the same page useful to those who want to see the XML & those who don't (or other sections).

- There might be a way to pass through CSS display block/none instructions, with a java script function to toggle them (the approach I've taken at https://github.com/PeterParslow/GEMINI2-3/blob/main/1-title.html). See https://www.metanorma.org/builder/topics/styling-output-html/

But to use CSS this way seems far more complex than just managing / editing native HTML!

**Comment by archaeogeek** [comment]
If asciidoc is going to make things more complicated then I don't see the point of going down that route or the metanorma approach. There are other options, such as sphinx (https://www.sphinx-doc.org/en/master/). Yes we'd need to use something like https://stackoverflow.com/questions/2454577/sphinx-restructuredtext-show-hide-code-snippets to do show/hide but it's clearly possible. 

FWIW I didn't get very far with the ruby issue I hit in metanorma, so would not be unhappy to change approaches at this stage :-)

**Comment by PeterParslow** [comment]
Hold that thought - I know Ronald Tse pretty well, who is very engaged with Metanorma. I'll try to phrase our request in such a way as to get an idea from him whether it should be possible (preferably 'reasonably easy').

**Comment by archaeogeek** [comment]
I've also got a potential solution to the ruby bug I was seeing, so I'll see if I can make some progress with that as well

**Comment by PeterParslow** [comment]
@archaeogeek I've done a bit more looking on embedding 'active content' (restyled by parameter) into the ASCIIdoc files. This seems to be possible, using a combination of docinfo.html and ASCII doc 'role' variables. However, I can't check that in GitPages without adding something extra to the Jekyll configuration which GitPages is using. And even if I did that, it wouldn't show whether the same approach will work through Metanorma.

That lead me to realise that we may be able to publish ASCIIdoc on GitHub without using Metanorma - but I suspect you looked into this. GitHub uses "safe mode" ASCIIdoctor, but seems quite configurable; GitPages then adds a bit to that.

Anyway, could you try my sample with Metanorma? It's two files at https://github.com/PeterParslow/GEMINI2-3: 1-titlePP.asciidoc and docinfo.html

https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/ implies that to get ASCIIdoctor to load the docinfo requires a command line parameter.

Meanwhile, I've come to like maintaining the GEMINI element page-fragments in ASCIIdoc, if only because I no longer have to escape almost everything in each XML example!

**Comment by PeterParslow** [comment]
Over the past few months, Jo has made a lot of progress. Basically, what's left is that we need to style the pages to "pass muster" for AGI Council, and decide how to manage 'pending' and published things. I know that GitHub is designed for that, so the difficult bit seems to be styling.

Over the past couple of weeks, I've spent an hour attempting to fathom out the style sheets on the live AGI site, but they have a the typical "system generated" complexity. I've then spent another hour trying to recreate the style from scratch, but my HTML/CSS is too rusty. Me doing it is way to inefficient.

Could all GEMINI Working Group people see if they have any HTML styling expertise available in their organisation? For someone who knows what he or she is doing, it can't be that hard! Then of course, we need to make sure we can recreate that from ASCIIDoc.

@nmtoken @6footdestiny @archaeogeek @coalsh

**Comment by archaeogeek** [comment]
My 2p worth is that it doesn't necessarily be a complex job. I think if we focus on getting the basic text styles correct (headers, paragraphs, text, links etc) then I can go to council and see if that's enough. If it's not, then they can tell me what else they need and we can work on that.

**Comment by archaeogeek** [comment]
I've made a start on the css (see https://agiorguk.github.io/gemini/datasets.html). I'm going for the low-tech approach of building up a new stylesheet (https://github.com/agiorguk/gemini/blob/main/docs/assets/gemini.css) by scratch, just overriding the elements from the original asciidoctor.css as required. I'll keep tinkering, but feel free to join in :-)

**Comment by nmtoken** [comment]
Is importing Google fonts going to be an issue for GDPR?

i.e. The `@import "https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700";` in asciidoctor.css

**Comment by PeterParslow** [comment]
James, could you explain? Are the Google fonts somehow likely to take away personal data? If so, I'd be curious as to how!

**Comment by nmtoken** [comment]
https://blog.runcloud.io/google-fonts-gdpr/

**Comment by PeterParslow** [comment]
Thanks. So OK if hosted locally, but not if we route each user via the Google site to get the fonts. May be easier to use a different font family.
