### ISSUE TITLE
Broken link in encoding guidelines for metadata point of contact

### ISSUE THREAD

**Issue by archaeogeek** [agiorguk/gemini#65]
In https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series/#35 there's a link to some more guidance on `responsible party` but this leads to a 404. It should point to https://www.agi.org.uk/gemini/40-gemini/1062-gemini-datasets-and-data-series/#23. Furthermore the corresponding element is `responsible organisation` rather than `responsible party`

**Comment by PeterParslow** [comment]
Link from https://agiorguk.github.io/gemini/1062-gemini-datasets-and-data-series.html#35 to https://agiorguk.github.io/gemini/1048-uk-gemini-encoding-guidance.html#_responsible_party works & seems appropriate. Reckon Jo fixed this during migration.
