### ISSUE TITLE
2020-17: inconsistency in Alternative Title

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#7]
We removed the DOI example, but the Encoding guidelines text still references it “example 2”

**Comment by 6footdestiny** [comment]
Update encoding guidelines. At least until such time as DOIs make a proper entrance into general usage

**Comment by PeterParslow** [comment]
Agreed to delete "for example to record a formal DOI citation string"

ONS & Government Data Architecture Community are thinking to promote DOIs, so it's sensible to tidy this up soon.

We should check whether what we do say in _Resource identifier_ and _Resource locator_ makes sense. There is a further mention of DOI in _Additional information_, but that is for citing the other document that contains the additional info. https://github.com/agiorguk/gemini/issues/59

**Comment by PeterParslow** [comment]
We actually have to delete the whole sentence, as example 2 doesn't illustrate what the sentence says it does. 

"The ISO 19115 sub-element otherCitationDetails may be used, for example to record a formal DOI citation string, as in example 2 below". 

I've added two HTML pages revised accordingly (well, I wanted to, but GItHub doesn't allow HTML pages to be attached - so I've put them in https://github.com/agiorguk/gemini/tree/main/pending; I guess this would properly be a pull request?

We could adjust the first sentence to have "example" in the plural - but we only give one example for service records.

Or I guess come up with a useful scenario for _otherCitationDetails_; I don't have one - the only one we had was to provide a DOI.

Question: If I publish this without waiting for a release, should I use the existing versioning system? If so, the "version date" at the top will be set to today, and I'll include a description of the change in the change log.

**Comment by PeterParslow** [comment]
Emailed to Blue Star (AGI web support)

**Comment by PeterParslow** [comment]
Fixed during migration to GitHub publication.
