### ISSUE TITLE
GEMINI 2.3 accepted by Open Standards Board

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#82]
The minutes of the UK government Open Standards Board's July 2022 meeting confirm that they have accepted GEMINI 2.3 as an open standard for use in government.

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1106393/Open_Standards_Board_Minutes_7_July_2022.odt

This could be mentioned in the GEMINI 2.3 home page.

**Comment by archaeogeek** [comment]
We could add it in a couple of places:

- https://www.agi.org.uk/uk-gemini/
- https://www.agi.org.uk/agi-uk-gemini/
- https://www.agi.org.uk/why-uk-gemini/

How about we adjust the following sentence: “GEMINI” is the UK geographic metadata standard. It provides guidance on how to publish geographic metadata in a way that conforms to UK government guidelines and the relevant ISO standards.

to say something like:

“GEMINI” is the UK geographic metadata standard. It provides guidance on how to publish geographic metadata in a way that conforms to UK government guidelines and the relevant ISO standards. As of July 2022 "GEMINI" is an accepted open standard for use in government.

**Comment by PeterParslow** [comment]
DSA link: https://www.gov.uk/government/publications/recommended-open-standards-for-government/using-metadata-to-describe-data-shared-within-government

The "difference" is an odd one: the Open Standards Board recommends, the Data Standards Authority is the authority. But for this one, the DSA made its recommendation first - whilst the OSB was "in abeyance". At that time, the OSB was the only one that could mandate standards for central government procurement - but Im not sure that's true anymore!
